name: Publish documentation to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        - uses: actions/checkout@v2
      - name: Setup
        - uses: actions/setup-node@v1
          with:
            node-version: '12'
        - run: npm install jsdoc

      - name: Generate docs
        - run: npm docs:build:linux

      - name: Publish docs to GH pages
        uses: tsunematsu21/actions-publish-gh-pages@v0.1.0
        with:
          dir: docs/dev
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}